import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Tindahan Ledger",
	description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
			<body>
				<header className="flex gap-8 border-b border-neutral-200 px-16 py-4">
					<Link href="/">Home</Link>
					<Link href="/customers">Customers</Link>
				</header>
				{children}
			</body>
		</html>
	);
}
